# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.vm.box = "prashantkalkar/ecsworkshopbox"
  #config.vm.box_version = "20181105.0.0"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.

  config.vm.synced_folder "../..", "/home/vagrant/repos"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.

  config.vm.provision "pull-jenkins-image", type: "shell", inline: <<-SHELL
    docker pull jenkins/jenkins:lts
  SHELL

  config.vm.provision "copy-credentials", type: "file", source: "~/accessKeys.csv", destination: "/tmp/accessKeys.csv"

  config.vm.provision "set-credentials", type: "shell", privileged: false, inline: <<-SHELL
    ACCESS_KEY="$(csvtool sub 2 1 1 1 /tmp/accessKeys.csv)"
    SECRET_KEY="$(csvtool sub 2 2 1 1 /tmp/accessKeys.csv)"

    aws configure set aws_access_key_id ${ACCESS_KEY}
    aws configure set aws_secret_access_key ${SECRET_KEY}
    aws configure set default.region us-east-1
    aws configure set default.output json
  SHELL

  # NOTE: Please copy workspace_config.template to your user home and substitute the required values.
  config.vm.provision "copy-workshop-config", type: "file", source: "~/workspace_config", destination: "~/workspace_config"

  config.vm.provision "setup-workspace-environment", type: "shell", privileged: false, inline: <<-SHELL
    dos2unix ~/workspace_config
    echo "source ~/workspace_config" >> ~/.zshrc
  SHELL

  config.vm.provision "set-jenkins-ecr-repo", type: "shell", privileged: false, inline: <<-SHELL
    echo "JENKINS_ECR_REPOSITORY_PATH='738035286324.dkr.ecr.us-east-1.amazonaws.com/ecs-workshop/jenkins'" >> ~/.zshrc
  SHELL

  config.vm.provision "create-ssh-key-for-github", type: "shell", privileged: false, inline: <<-SHELL
    source ~/workspace_config
    ssh-keygen -t rsa -b 4096 -C "${GITHUB_USER_EMAIL}" -N "" -f ~/.ssh/id_rsa
  SHELL

end